### ISSUE TITLE
lmdb.CorruptedError

### ISSUE THREAD

**Issue by nischal-sanil** [clovaai/deep-text-recognition-benchmark#113]
Hello,

I was trying to train the ST_spe dataset from [here](https://drive.google.com/drive/folders/192UfE9agQUMNq6AgU3_E05_FcPZK4hyt) using the following command:

```
!CUDA_VISIBLE_DEVICES=0 python3 /content/deep-text-recognition-benchmark/train.py \
--train_data /data_lmdb_release/training \
--valid_data/data_lmdb_release/validation \
--select_data MJ-ST_spe --batch_ratio 0.5-0.5 \
--Transformation TPS --FeatureExtraction ResNet --SequenceModeling BiLSTM --Prediction Attn
```

Got an Error as shown:

```
Filtering the images containing characters which are not in opt.character
Filtering the images whose label is longer than opt.batch_max_length
--------------------------------------------------------------------------------
dataset_root: /content/drive/My Drive/FYLE/text identification/data_lmdb_release/training
opt.select_data: ['MJ', 'ST_spe']
opt.batch_ratio: ['0.5', '0.5']
--------------------------------------------------------------------------------
dataset_root:    /content/drive/My Drive/FYLE/text identification/data_lmdb_release/training	 dataset: MJ
Traceback (most recent call last):
  File "/content/deep-text-recognition-benchmark/train.py", line 307, in <module>
    train(opt)
  File "/content/deep-text-recognition-benchmark/train.py", line 31, in train
    train_dataset = Batch_Balanced_Dataset(opt)
  File "/content/deep-text-recognition-benchmark/dataset.py", line 37, in __init__
    _dataset = hierarchical_dataset(root=opt.train_data, opt=opt, select_data=[selected_d])
  File "/content/deep-text-recognition-benchmark/dataset.py", line 102, in hierarchical_dataset
    dataset = LmdbDataset(dirpath, opt)
  File "/content/deep-text-recognition-benchmark/dataset.py", line 139, in __init__
    label = txn.get(label_key).decode('utf-8')
lmdb.CorruptedError: mdb_get: MDB_CORRUPTED: Located page was wrong type
```

Can anyone explain what the issue is and how do I correct it?

Also, Is there a pre-trained model that was trained on the ST_spe dataset?

Thanks,

**Comment by 649498612** [comment]
I met the same problem. Have you solved it up to now?

**Comment by peternara** [comment]
me too!!!! ??solve
