### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by vinodckumar** [clovaai/deep-text-recognition-benchmark#115]
Traceback (most recent call last):
  File "C:\Users\LENOVO\Downloads\deep-text-recognition-benchmark-master\deep-text-recognition-benchmark-master\train.py", line 307, in <module>
    train(opt)
  File "C:\Users\LENOVO\Downloads\deep-text-recognition-benchmark-master\deep-text-recognition-benchmark-master\train.py", line 31, in train
    train_dataset = Batch_Balanced_Dataset(opt)
  File "C:\Users\LENOVO\Downloads\deep-text-recognition-benchmark-master\deep-text-recognition-benchmark-master\dataset.py", line 27, in __init__
    assert len(opt.select_data) == len(opt.batch_ratio)
AssertionError

**Comment by wyc2015fq** [comment]
同问？
Filtering the images containing characters which are not in opt.character
Filtering the images whose label is longer than opt.batch_max_length
--------------------------------------------------------------------------------
dataset_root: data_lmdb_release/training
opt.select_data: ['MJ']
opt.batch_ratio: ['0.5', '0.5']
Traceback (most recent call last):
  File "train.py", line 307, in <module>
    train(opt)
  File "train.py", line 31, in train
    train_dataset = Batch_Balanced_Dataset(opt)
  File "/home/ssd1/data/wanyangchun/com/deep-text-recognition-benchmark-master/dataset.py", line 27, in __init__
    assert len(opt.select_data) == len(opt.batch_ratio)
AssertionError

**Comment by Deng-Qian** [comment]
> ## 同问？
> Filtering the images containing characters which are not in opt.character
> Filtering the images whose label is longer than opt.batch_max_length
> dataset_root: data_lmdb_release/training
> opt.select_data: ['MJ']
> opt.batch_ratio: ['0.5', '0.5']
> Traceback (most recent call last):
> File "train.py", line 307, in
> train(opt)
> File "train.py", line 31, in train
> train_dataset = Batch_Balanced_Dataset(opt)
> File "/home/ssd1/data/wanyangchun/com/deep-text-recognition-benchmark-master/dataset.py", line 27, in **init**
> assert len(opt.select_data) == len(opt.batch_ratio)
> AssertionError

同问，请问你解决了吗
