### ISSUE TITLE
Type error:

### ISSUE THREAD

**Issue by Ma01180724** [clovaai/deep-text-recognition-benchmark#126]
Traceback (most recent call last):
  File "/home/mxt/dataset/deep-text-recognition-benchmark-master/train.py", line 283, in <module>
    train(opt)
  File "/home/mxt/dataset/deep-text-recognition-benchmark-master/train.py", line 26, in train
    train_dataset = Batch_Balanced_Dataset(opt)
  File "/home/mxt/dataset/deep-text-recognition-benchmark-master/dataset.py", line 37, in __init__
    _dataset = hierarchical_dataset(root=opt.train_data, opt=opt, select_data=[selected_d])
  File "/home/mxt/dataset/deep-text-recognition-benchmark-master/dataset.py", line 102, in hierarchical_dataset
    dataset = LmdbDataset(dirpath, opt)
  File "/home/mxt/dataset/deep-text-recognition-benchmark-master/dataset.py", line 123, in __init__
    nSamples = int(txn.get('num-samples'.encode()))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by hyungkwonko** [comment]
As I had the same issue, you may consider regenerating .lmdb dataset which for me was the problem.

**Comment by Aldemaro14** [comment]
@hyungkwonko hey man, i having the same issue, also tried to regenerate the data, but still the same problem, any advice????

**Comment by hyungkwonko** [comment]
@Aldemaro14 in my case, the size of .lmdb file was 0. If you were in the same situation, you may reconsider checking the sanity of .lmdb files. Otherwise you may have different issue (library version, etc). Hope it helps.
