### ISSUE TITLE
lmdb.Error: training/.ipynb_checkpoints: No such file or directory

### ISSUE THREAD

**Issue by 18162171029** [clovaai/deep-text-recognition-benchmark#192]
!python train.py --train_data='training' --valid_data='training' --Transformation='TPS' --FeatureExtraction='ResNet' --SequenceModeling='BiLSTM' --Prediction='Attn'

----------------------------------------------------------------------------------------------------------------------------------------

Filtering the images containing characters which are not in opt.character
Filtering the images whose label is longer than opt.batch_max_length
['1']

dataset_root: training
opt.select_data: ['/']
opt.batch_ratio: ['1']

dataset_root:    training	 dataset: /
Traceback (most recent call last):
  File "train.py", line 305, in <module>
    train(opt)
  File "train.py", line 33, in train
    train_dataset = Batch_Balanced_Dataset(opt)
  File "/content/drive/My Drive/internship/deep_text_recognition_benchmark_master/dataset.py", line 42, in __init__
    _dataset, _dataset_log = hierarchical_dataset(root=opt.train_data, opt=opt, select_data=[selected_d])
  File "/content/drive/My Drive/internship/deep_text_recognition_benchmark_master/dataset.py", line 118, in hierarchical_dataset
    dataset = LmdbDataset(dirpath, opt)
  File "/content/drive/My Drive/internship/deep_text_recognition_benchmark_master/dataset.py", line 135, in __init__
    self.env = lmdb.open(root, max_readers=32, readonly=True, lock=False, readahead=False, meminit=False)
lmdb.Error: training/.ipynb_checkpoints: No such file or directory

but when i do ls -a command in training directory then their it shows .ipynb_checkpoints

please help me out!!!!

**Comment by Tamoghna-Saha** [comment]
You need to first run the `create_lmbd_dataset.py` with your own custom dataset and then train the model.
See this [issue](https://github.com/clovaai/deep-text-recognition-benchmark/issues/85). It's mentioned in the README.

**Comment by Rhcsky** [comment]
Perhaps there are `.ipynb_checkpoints` in your training/ folder.
Not visible in colab. Go into Google drive and check then you'll see it.
Remove that and try running it again.

**Comment by AbdelsalamHaa** [comment]
Hi, @Tamoghna-Saha  I'm facing the exact same issue, I have run the creat_lmdp_dataset.py already, and got the outputfile as results.mdp I changed the and made it as training.mdp. 
after that I moved the file to have the directory  data_lmdb_release/training/training.mdp
but the same issue still appears

self.env = lmdb.open(root, max_readers=32, readonly=True, lock=False, readahead=False, meminit=False)
lmdb.Error: data_lmdb_release/training/: No such file or directory

I have also looked at this https://github.com/clovaai/deep-text-recognition-benchmark/issues/85 and edit the code accordingly but the issue is still there, I hope you can help in this thanks a lot.

**Comment by premtibadiya** [comment]
@AbdelsalamHaa did you solved your error?

**Comment by premtibadiya** [comment]
@AbdelsalamHaa even I am having the same error can you help me if you solved your error?

**Comment by SaeedArisha** [comment]
write this line of code in colab/jupyter whatever you are using and it will return True, meaning that the .ipynb_checkpoint folder is probably hidden. 
import os
os.path.isdir('.ipynb_checkpoints')
Once detected use os.remove to delete it

**Comment by SaeedArisha** [comment]
**os.removedirs('.ipynb_checkpoints'), removedirs since, it's a directory we have to remove
