### ISSUE TITLE
forward() missing 2 required positional arguments: 'input' and 'text'

### ISSUE THREAD

**Issue by dikers** [clovaai/deep-text-recognition-benchmark#200]
When I use demo.py predict my images, 
I modify 'batch_size' from 192->2, 

'parser.add_argument('--batch_size', type=int, default=2, help='input batch size')'
'parser.add_argument('--batch_size', type=int, default=2, help='input batch size')'

The following error results occurred:
`Traceback (most recent call last):
  File "demo.py", line 138, in <module>
    demo(opt)
  File "demo.py", line 68, in demo
    preds = model(image, text_for_pred, is_train=False)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/ec2-user/.local/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/ec2-user/.local/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in replica 2 on device 2.
Original Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 2 required positional arguments: 'input' and 'text'
`

Please help me check it? Thank you

**Comment by ku21fan** [comment]
Hello, 

I have two questions to resolve this problem.
1) Does this error occur when you try with batch_size 192?
Even if you try with batch_size 192, you would divide (odd_number/192) and also cannot be divisible, so I want to check whether batch_size is the cause of the problem or not.

2) Does this error occur when you use a single GPU?
Maybe a single GPU would not occur this error.

Best

**Comment by JoshuaPlacidi** [comment]
Hi,

I am currently experiencing the same error during training:

```
start_iter = 0
start_time = time.time()
best_accuracy = -1
best_norm_ED = -1
iteration = start_iter
torch.cuda.empty_cache()
#while(True):
for img_path_batch, img_batch, text_batch, objects_batch in tqdm(data_ldr):
    image = img_batch.to(device)
    print(text_batch)
    text, length = converter.encode(text_batch, batch_max_length=batch_max_length)
    
    if 'CTC' in prediction:
        preds = model(image, text)
        preds_size = torch.IntTensor([preds.size(1) * batch_size])
        
        preds = preds.log_softmax(2).permute(1, 0, 2)
        cost = criterion(preds, text, preds_size, length)
    else:
        preds = model(image, text[:, :-1], objects_batch)  # align with Attention.forward
        target = text[:, 1:]  # without [GO] Symbol
        cost = criterion(preds.view(-1, preds.shape[-1]), target.contiguous().view(-1))
        
        model.zero_grad()
        cost.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 5)  # gradient clipping with 5 (Default)
        optimizer.step()
        
        loss_avg.add(cost)
    iteration += 1

'finish training'
```
Error:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-60-2cfde1ea9c69> in <module>
     22         preds = model(image, text[:, :-1], objects_batch)  # align with Attention.forward
     23         target = text[:, 1:]  # without [GO] Symbol
---> 24         cost = criterion(preds.view(-1, preds.shape[-1]), target.contiguous().view(-1))
     25 
     26         model.zero_grad()

~\anaconda3\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

TypeError: forward() missing 2 required positional arguments: 'input_lengths' and 'target_lengths'
```

Did you find a solution for it? I have lowered my batch size from 192 to 64 because of shortage of GPU memory, is the problem caused by changing batch size?

**Comment by GraceKafuu** [comment]
Facing the same problem.

**Comment by ttxskk** [comment]
Maybe you just need to set drop_last=True in your DataLoader.
