### ISSUE TITLE
Missing key error when run demo

### ISSUE THREAD

**Issue by NguyenHongSon1103** [clovaai/deep-text-recognition-benchmark#212]
Hi ! I trained your model with my own dataset and then run demo with:

python demo.py --image_folder "\OCR_Model\ROIS" --saved_model "\OCR_Model\TPS-ResNet-BiLSTM-Attn-Seed1111\best_accuracy.pth" --imgH 50 --imgW 1000 --character "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ<" --rgb --Transformation TPS --FeatureExtraction ResNet --SequenceModeling BiLSTM --Prediction Attn

but have errror like: 
model input parameters 50 1000 20 3 512 256 39 25 TPS ResNet BiLSTM Attn
loading pretrained model from \OCR_Model\TPS-ResNet-BiLSTM-Attn-Seed1111\best_accuracy.pth
Traceback (most recent call last):
  File "demo.py", line 134, in <module>
    demo(opt)
  File "demo.py", line 36, in demo
    model.load_state_dict(torch.load(opt.saved_model, map_location=device))
  File "C:\Users\Luxury\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
        Missing key(s) in state_dict: "module.Transformation.GridGenerator.inv_delta_C", "module.Transformation.GridGenerator.P_hat".

I use exactly this config for training but on Linux OS, is this my problem ? 
Thank you for help !

**Comment by NguyenHongSon1103** [comment]
I found it ! Which some unknown reason, my key on .pht file has "module." in begining so not match with require. 
ie model need : "Transformation.GridGenerator.inv_delta_C" and my weights has: "module.Transformation.GridGenerator.inv_delta_C". So I just add strict=False in model.load_state_dict()

**Comment by HariniNarasimhan** [comment]
Did you solve the problem? . I get them too!

**Comment by NguyenHongSon1103** [comment]
> Did you solve the problem? . I get them too!

I found that problem come from run model without gpu. In file tranformation.py, below line 97 are some layers implement for run on gpu, and I modified it to: 
 ## for multi-gpu, you need register buffer
        # self.register_buffer("inv_delta_C", torch.tensor(self._build_inv_delta_C(self.F, self.C)).float())  # F+3 x F+3
        # self.register_buffer("P_hat", torch.tensor(self._build_P_hat(self.F, self.C, self.P)).float())  # n x F+3
        ## for fine-tuning with different image width, you may use below instead of self.register_buffer
        if torch.cuda.is_available():
            self.inv_delta_C = torch.tensor(self._build_inv_delta_C(self.F, self.C)).float().cuda()  # F+3 x F+3
            self.P_hat = torch.tensor(self._build_P_hat(self.F, self.C, self.P)).float().cuda()  # n x F+3
        else:
            self.inv_delta_C = torch.tensor(self._build_inv_delta_C(self.F, self.C)).float()  # F+3 x F+3
            self.P_hat = torch.tensor(self._build_P_hat(self.F, self.C, self.P)).float()  # n x F+3

Another solution is set strict=False in load_state_dict() funtion. Hope this help you
