### ISSUE TITLE
size mismatch for module.Prediction

### ISSUE THREAD

**Issue by lambdaterm** [clovaai/deep-text-recognition-benchmark#221]
Hello!

First of all, many thanks for your incredible repo! I've decided to train None-ResNet-BiLSTM-Attn network on my own dataset. After training was finished I try to use a new network to check how it works, but I get this error message:

```
$ python3 demo.py --Transformation None --FeatureExtraction ResNet --SequenceModeling BiLSTM --Prediction Attn --image_folder demo_image/ --saved_model best_accuracy.pth
No Transformation module specified
model input parameters 32 100 20 1 512 256 38 25 None ResNet BiLSTM Attn
loading pretrained model from best_accuracy.pth
Traceback (most recent call last):
  File "demo.py", line 131, in <module>
    demo(opt)
  File "demo.py", line 34, in demo
    model.load_state_dict(torch.load(opt.saved_model, map_location=device))
  File "/home/alex/dev/repos/tmp/deep-text-recognition-benchmark/venv38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1044, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DataParallel:
	size mismatch for module.Prediction.attention_cell.rnn.weight_ih: copying a param with shape torch.Size([1024, 300]) from checkpoint, the shape in current model is torch.Size([1024, 294]).
	size mismatch for module.Prediction.generator.weight: copying a param with shape torch.Size([44, 256]) from checkpoint, the shape in current model is torch.Size([38, 256]).
	size mismatch for module.Prediction.generator.bias: copying a param with shape torch.Size([44]) from checkpoint, the shape in current model is torch.Size([38]).
```

How can I resolve this problem?

**Comment by ku21fan** [comment]
Hello :) 

This error message shows the number of characters is different from the default setting.
So, changing `--character` option of `demo.py` with respect to your own dataset will solve this problem.

Hope it helps,
Best.

**Comment by lambdaterm** [comment]
Yes, you are absolutely right. I forgot to update the `character` option.

Thanks for helping and have a nice day!
