### ISSUE TITLE
KeyError: 'b'

### ISSUE THREAD

**Issue by freedom9393** [clovaai/deep-text-recognition-benchmark#233]
When I try to train my model with Korean characters, following errors comes up:

```
Traceback (most recent call last):
  File "train.py", line 313, in <module>
    train(opt)
  File "train.py", line 149, in train
    text, length = converter.encode(labels, batch_max_length=opt.batch_max_length)
  File "D:\Projects\deep-text-recognition-benchmark-master\deep-text-recognition-benchmark-master\utils.py", line 136, in encode
    text = [self.dict[char] for char in text]
  File "D:\Projects\deep-text-recognition-benchmark-master\deep-text-recognition-benchmark-master\utils.py", line 136, in <listcomp>
    text = [self.dict[char] for char in text]
KeyError: 'b'
```

Why is this happening??

**Comment by SrijithBalachander** [comment]
Your dataset probably has a character 'b' while your character set doesn't have 'b' defined.
