### ISSUE TITLE
Couldn't transform to onnx model from .pth model. TypeError: bool object is not subscriptable 

### ISSUE THREAD

**Issue by puri-gagan** [clovaai/deep-text-recognition-benchmark#266]
model input parameters 32 100 20 1 512 256 15 25 TPS ResNet BiLSTM Attn
loading pretrained model from saved_models/TPS-ResNet-BiLSTM-Attn-Seed1111/best_accuracy.pth
output path : ./onnx_output/onnx_output/
Traceback (most recent call last):
  File "transform_to_onnx.py", line 106, in <module>
    transform_to_onnx(opt)
  File "transform_to_onnx.py", line 62, in transform_to_onnx
    dummy_output = model(dummy_input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "transform_to_onnx.py", line 21, in forward
    output = self.model(input, is_tran)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/drive/MyDrive/yolo/deep-text-recognition-benchmark/model.py", line 102, in forward
    prediction = self.Prediction(contextual_feature.contiguous(), text, is_train, batch_max_length=self.opt.batch_max_length)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/drive/MyDrive/yolo/deep-text-recognition-benchmark/modules/prediction.py", line 40, in forward
    char_onehots = self._char_to_onehot(text[:, i], onehot_dim=self.num_classes)
TypeError: 'bool' object is not subscriptable

**Comment by korotaS** [comment]
Which dummy input do you use in "model(dummy_input)" call? Seems like the problem is with it
