### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'num_class'

### ISSUE THREAD

**Issue by yustiks** [clovaai/deep-text-recognition-benchmark#272]
I try to run the training on a custom data, 
I run the next code:
```
CUDA_VISIBLE_DEVICES=0 python3 deep_text_recognition_benchmark/train.py --train_data deep_text_recognition_benchmark/training_data_15_03/   --valid_data deep_text_recognition_benchmark/valid_data_14_03/ --Transformation None --FeatureExtraction VGG --SequenceModeling BiLSTM --Prediction CTC --num_iter 500000 --batch_size 256
```
and I have this error:
```
Traceback (most recent call last):
  File "deep_text_recognition_benchmark/train.py", line 320, in <module>
    train(opt)
  File "deep_text_recognition_benchmark/train.py", line 58, in train
    model = Model(opt)
TypeError: __init__() missing 1 required positional argument: 'num_class'
```
my torch version is:
1.2.0+cu92
torch vision:
0.4.0+cu92

How to solve it?

**Comment by yustiks** [comment]
I have found an answer.
Basically, Model method required num_classes parameter in addition to opt
