### ISSUE TITLE
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute 'next'

### ISSUE THREAD

**Issue by krammnic** [clovaai/deep-text-recognition-benchmark#355]
PyTorch version: 1.13.0.dev20220810+cu116
Train command: python train.py --train_data  data_lmdb_release/training/MJ/MJ_train --valid_data data_lmdb_release/training/MJ/MJ_valid --select_data MJ-MJ --batch_ratio 0.5-0.5 --Transformation TPS --FeatureExtraction ResNet --SequenceModeling BiLSTM --Prediction Attn 
Full log:

```
Traceback (most recent call last):
  File "/home/krammnic/PycharmProjects/yolov6/deep-text-recognition-benchmark/train.py", line 318, in <module>
    train(opt)
  File "/home/krammnic/PycharmProjects/yolov6/deep-text-recognition-benchmark/train.py", line 147, in train
    image_tensors, labels = train_dataset.get_batch()
  File "/home/krammnic/PycharmProjects/yolov6/deep-text-recognition-benchmark/dataset.py", line 88, in get_batch
    image, text = data_loader_iter.next()  # .next()
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute 'next'
```

**Comment by scuxxs** [comment]
I have the same issue

**Comment by scuxxs** [comment]
have you solved it？

**Comment by jkwhuer** [comment]
I would appreciate it if you could tell me how to solve this problem

**Comment by hkdzl** [comment]
data_loader_iter.next()--->next(data_loader_iter)
