### ISSUE TITLE
 set_storage is not allowed on Tensor created from .data or .detach()

### ISSUE THREAD

**Issue by Crescentz** [clovaai/deep-text-recognition-benchmark#55]
model input parameters 32 100 20 1 512 256 96 25 TPS ResNet BiLSTM Attn
loading pretrained model from /home1/zy/STR/psenet_benchmark/benchmark/pretrained_model/TPS-ResNet-BiLSTM-Attn-case-sensitive.pth
Traceback (most recent call last):
  File "/home1/zy/STR/psenet_benchmark/api.py", line 22, in <module>
    br(image_folder)
  File "/home1/zy/STR/psenet_benchmark/api.py", line 15, in br
    getrecognition(image_folder)
  File "/home1/zy/STR/psenet_benchmark/benchmark/getrecognition.py", line 121, in getrecognition
    demo(opt)
  File "/home1/zy/STR/psenet_benchmark/benchmark/getrecognition.py", line 64, in demo
    preds = model(image, text_for_pred, is_train=False)
  File "/home1/zy/miniconda3/envs/STR/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home1/zy/miniconda3/envs/STR/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home1/zy/miniconda3/envs/STR/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home1/zy/miniconda3/envs/STR/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/home1/zy/miniconda3/envs/STR/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/home1/zy/miniconda3/envs/STR/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "./benchmark/model.py", line 82, in forward
    contextual_feature = self.SequenceModeling(visual_feature)
  File "/home1/zy/miniconda3/envs/STR/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home1/zy/miniconda3/envs/STR/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home1/zy/miniconda3/envs/STR/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "./benchmark/modules/sequence_modeling.py", line 16, in forward
    self.rnn.flatten_parameters()
  File "/home1/zy/miniconda3/envs/STR/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 123, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: set_storage is not allowed on Tensor created from .data or .detach()

**Comment by ku21fan** [comment]
Hello, 

It seems to Pytorch bug. https://github.com/pytorch/pytorch/issues/21108
How about upgrade Pytorch to 1.2.0?

Best

**Comment by Crescentz** [comment]
thank you；
it works！

**Comment by dviettu134** [comment]
Hi, it seems that Pytorch v1.2.0 need Cuda ver 10 to work,
But our environment does not support Cude ver 10 installation.

Is there any other solutions to this issue while keep using Pytorch v1.1.0?

Best regards,

**Comment by dviettu134** [comment]
PS: By downgrading pytorch version to 1.0.1, the error is gone.
 But does it cause any problems to the training/evaluation procedure?

Best regards,

**Comment by ku21fan** [comment]
@dviettu134 Hello, 

I just noticed your comment, 

1. I don't know the other solution while keep using Pytorch v1.1.0... :'(

2. I guess that it does not cause any problems to the training/evaluation procedure. 

Best.
